baseurl               = "https://webstack.grapehut.xyz/"
languageCode          = "zh-CN"
title                 = "小饅頭の部屋"
theme                 = "WebStack-Hugo-theme"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    homeurl       = "https://webstack.grapehut.xyz/"
    author        = "小饅頭の部屋"
    description   = "小饅頭の部屋"
    upload        = ""
    about         = ""                                     # 左侧导航栏的"关于我们"页面(./about)
    repository    = ""
    enablePreLoad = true                                   # 网站完全打开前预加载动画
    textPreLoad   = "小饅頭の部屋 Loading..."               # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = true                                   # 默认展开左侧边导航栏
    logosPath     = "./assets/logos"                       # 网站每个导航地址logo存放地址
    defaultLogo   = "./assets/logos/FindIcons.png"         # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false                                  # 默认站点为深色模式
    yiyan         = true                                   # 默认启用一言服务

[params.seo]
    baiduhmid       = ''         # 百度统计 hm.src 的 ID
    baiduSiteVer    = ''         # 百度HTML标签验证(baidu-site-verification) 
    tj51laid        = ''         # 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = 'ca-pub-9661896697976587'

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "./assets/images/favicon.svg"
    searchImageL      = "./assets/images/home-bg.jpg"               # 搜索部分浅色背景图
    searchImageD      = "./assets/images/home-bg.jpg"               # 搜索部分深色背景图
    logoExpandLight   = "./assets/images/favicon.png"
    logoExpandDark    = "./assets/images/favicon.png"
    logoCollapseLight = "./assets/images/favicon.png"
    logoCollapseDark  = "./assets/images/favicon.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = 'Copyright © 2024～{year} [小饅頭の部屋](https://www.grapehut.xyz) <br>[萌ICP备20241189号](https://icp.gov.moe/?keyword=20241189) | Power By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo)'
